import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useGetPostsQuery } from "@/features/api/apiSlice";

export default function Home() {
  const {
    data: posts,
    isLoading,
    isSuccess,
    isError,
    error,
  } = useGetPostsQuery();

  console.log(posts, isLoading, isSuccess, isError, error);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
